/*******************************************************************************
 * Copyright (c) 2004-2006 Sunil Kamath (IcemanK).
 * All rights reserved.
 * This program is made available under the terms of the Common Public License
 * v1.0 which is available at http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     Sunil Kamath (IcemanK) - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_eclipsensis_makensis_MakeNSISRunner */

#ifndef _Included_net_sf_eclipsensis_makensis_MakeNSISRunner
#define _Included_net_sf_eclipsensis_makensis_MakeNSISRunner
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: cProcess */
/* Inaccessible static: cBestCompressorFormat */
/* Inaccessible static: cProcessLock */
/* Inaccessible static: cHwnd */
/* Inaccessible static: cListeners */
#undef net_sf_eclipsensis_makensis_MakeNSISRunner_COMPRESSOR_DEFAULT
#define net_sf_eclipsensis_makensis_MakeNSISRunner_COMPRESSOR_DEFAULT 0L
/* Inaccessible static: COMPRESSOR_BEST */
/* Inaccessible static: COMPRESSOR_DISPLAY_ARRAY */
/* Inaccessible static: COMPRESSOR_NAME_ARRAY */
/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISRunner
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISRunner_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISRunner
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISRunner_destroy
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISRunner
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISRunner_reset
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISRunner
 * Method:    getScriptFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISRunner_getScriptFileName
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISRunner
 * Method:    getOutputFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISRunner_getOutputFileName
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISRunner
 * Method:    getErrors
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISRunner_getErrors
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISRunner
 * Method:    getWarnings
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISRunner_getWarnings
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
