/*******************************************************************************
 * Copyright (c) 2004-2008 Sunil Kamath (IcemanK).
 * All rights reserved.
 * This program is made available under the terms of the Common Public License
 * v1.0 which is available at http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     Sunil Kamath (IcemanK) - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_eclipsensis_makensis_MakeNSISProcess */

#ifndef _Included_net_sf_eclipsensis_makensis_MakeNSISProcess
#define _Included_net_sf_eclipsensis_makensis_MakeNSISProcess
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_000240 */
/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISProcess
 * Method:    init
 * Signature: (Ljava/lang/Class;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISProcess_init
  (JNIEnv *, jclass, jclass, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISProcess
 * Method:    exitValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISProcess_exitValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISProcess
 * Method:    waitFor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISProcess_waitFor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISProcess
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISProcess_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISProcess
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISProcess_create
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISProcess
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISProcess_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
