/*******************************************************************************
 * Copyright (c) 2004-2010 Sunil Kamath (IcemanK).
 * All rights reserved.
 * This program is made available under the terms of the Common Public License
 * v1.0 which is available at http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     Sunil Kamath (IcemanK) - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_eclipsensis_makensis_MakeNSISDelegateU */

#ifndef _Included_net_sf_eclipsensis_makensis_MakeNSISDelegateU
#define _Included_net_sf_eclipsensis_makensis_MakeNSISDelegateU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISDelegateU
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_init
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISDelegateU
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_destroy
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISDelegateU
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_reset
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISDelegateU
 * Method:    getErrors
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getErrors
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISDelegateU
 * Method:    getOutputFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getOutputFileName
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISDelegateU
 * Method:    getScriptFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getScriptFileName
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_makensis_MakeNSISDelegateU
 * Method:    getWarnings
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getWarnings
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
