/* Generated By:JavaCC: Do not edit this line. NSISHelpSearchQueryParserConstants.java */
package net.sf.eclipsensis.help.search.parser;

public interface NSISHelpSearchQueryParserConstants {

  int EOF = 0;
  int _NUM_CHAR = 1;
  int _ESCAPED_CHAR = 2;
  int _TERM_START_CHAR = 3;
  int _TERM_CHAR = 4;
  int AND = 9;
  int OR = 10;
  int NOT = 11;
  int PLUS = 12;
  int MINUS = 13;
  int LPAREN = 14;
  int RPAREN = 15;
  int COLON = 16;
  int CARAT = 17;
  int QUOTED = 18;
  int TERM = 19;
  int FUZZY_SLOP = 20;
  int WILDTERM = 21;
  int RANGEIN_START = 22;
  int RANGEEX_START = 23;
  int NUMBER = 24;
  int RANGEIN_TO = 25;
  int RANGEIN_END = 26;
  int RANGEIN_QUOTED = 27;
  int RANGEIN_GOOP = 28;
  int RANGEEX_TO = 29;
  int RANGEEX_END = 30;
  int RANGEEX_QUOTED = 31;
  int RANGEEX_GOOP = 32;

  int Boost = 0;
  int RangeEx = 1;
  int RangeIn = 2;
  int DEFAULT = 3;

  String[] tokenImage = {
    "<EOF>", //$NON-NLS-1$
    "<_NUM_CHAR>", //$NON-NLS-1$
    "<_ESCAPED_CHAR>", //$NON-NLS-1$
    "<_TERM_START_CHAR>", //$NON-NLS-1$
    "<_TERM_CHAR>", //$NON-NLS-1$
    "\" \"", //$NON-NLS-1$
    "\"\\t\"", //$NON-NLS-1$
    "\"\\r\"", //$NON-NLS-1$
    "\"\\n\"", //$NON-NLS-1$
    "<AND>", //$NON-NLS-1$
    "<OR>", //$NON-NLS-1$
    "<NOT>", //$NON-NLS-1$
    "\"+\"", //$NON-NLS-1$
    "\"-\"", //$NON-NLS-1$
    "\"(\"", //$NON-NLS-1$
    "\")\"", //$NON-NLS-1$
    "\":\"", //$NON-NLS-1$
    "\"^\"", //$NON-NLS-1$
    "<QUOTED>", //$NON-NLS-1$
    "<TERM>", //$NON-NLS-1$
    "<FUZZY_SLOP>", //$NON-NLS-1$
    "<WILDTERM>", //$NON-NLS-1$
    "\"[\"", //$NON-NLS-1$
    "\"{\"", //$NON-NLS-1$
    "<NUMBER>", //$NON-NLS-1$
    "\"TO\"", //$NON-NLS-1$
    "\"]\"", //$NON-NLS-1$
    "<RANGEIN_QUOTED>", //$NON-NLS-1$
    "<RANGEIN_GOOP>", //$NON-NLS-1$
    "\"TO\"", //$NON-NLS-1$
    "\"}\"", //$NON-NLS-1$
    "<RANGEEX_QUOTED>", //$NON-NLS-1$
    "<RANGEEX_GOOP>", //$NON-NLS-1$
  };

}
