/*******************************************************************************
 * Copyright (c) 2004-2010 Sunil Kamath (IcemanK).
 * All rights reserved.
 * This program is made available under the terms of the Common Public License
 * v1.0 which is available at http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     Sunil Kamath (IcemanK) - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_eclipsensis_util_winapi_x64_WinAPI64 */

#ifndef _Included_net_sf_eclipsensis_util_winapi_x64_WinAPI64
#define _Included_net_sf_eclipsensis_util_winapi_x64_WinAPI64
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: INSTANCE */
/* Inaccessible static: ZERO_HANDLE */
/* Inaccessible static: ZERO_LONGPTR */
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_GWL_EXSTYLE
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_GWL_EXSTYLE -20L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_GWL_STYLE
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_GWL_STYLE -16L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_GWL_WNDPROC
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_GWL_WNDPROC -4L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_NCHITTEST
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_NCHITTEST 132L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_SETFOCUS
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_SETFOCUS 7L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_KEYDOWN
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_KEYDOWN 256L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_CHAR
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_CHAR 258L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_SYSCHAR
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_SYSCHAR 262L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_LWA_COLORKEY
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_LWA_COLORKEY 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_LWA_ALPHA
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_LWA_ALPHA 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_EX_LAYERED
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_EX_LAYERED 524288L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_EX_LAYOUTRTL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_EX_LAYOUTRTL 4194304L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_HH_DISPLAY_TOPIC
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_HH_DISPLAY_TOPIC 0L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_HTTRANSPARENT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_HTTRANSPARENT -1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_SZ
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_SZ 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_EXPAND_SZ
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_EXPAND_SZ 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_BINARY
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_BINARY 3L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_DWORD
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_DWORD 4L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_MULTI_SZ
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_REG_MULTI_SZ 7L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_QUERY_VALUE
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_QUERY_VALUE 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_ENUMERATE_SUB_KEYS
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_ENUMERATE_SUB_KEYS 8L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_WOW64_32KEY
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_WOW64_32KEY 512L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_WOW64_64KEY
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_KEY_WOW64_64KEY 256L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_BS_LEFTTEXT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_BS_LEFTTEXT 32L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_CB_SHOWDROPDOWN
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_CB_SHOWDROPDOWN 335L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_CB_GETDROPPEDSTATE
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_CB_GETDROPPEDSTATE 343L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_PRINT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WM_PRINT 791L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_NONCLIENT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_NONCLIENT 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_CLIENT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_CLIENT 4L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_ERASEBKGND
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_ERASEBKGND 8L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_CHILDREN
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_PRF_CHILDREN 16L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_EP_EDITTEXT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_EP_EDITTEXT 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_ETS_NORMAL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_ETS_NORMAL 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_ETS_DISABLED
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_ETS_DISABLED 4L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_ETS_READONLY
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_ETS_READONLY 6L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_LVP_LISTITEM
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_LVP_LISTITEM 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_LIS_NORMAL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_LIS_NORMAL 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_LIS_DISABLED
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_LIS_DISABLED 4L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_BP_RADIOBUTTON
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_BP_RADIOBUTTON 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_UNCHECKEDNORMAL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_UNCHECKEDNORMAL 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_UNCHECKEDHOT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_UNCHECKEDHOT 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_CHECKEDNORMAL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_CHECKEDNORMAL 5L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_CHECKEDHOT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_RBS_CHECKEDHOT 6L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_TVS_HASBUTTONS
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_TVS_HASBUTTONS 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_TVS_HASLINES
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_TVS_HASLINES 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_COLOR_GRAYTEXT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_COLOR_GRAYTEXT 17L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_COLOR_3DHILIGHT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_COLOR_3DHILIGHT 20L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_HSCROLL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_HSCROLL 1048576L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_VSCROLL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_WS_VSCROLL 2097152L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_LB_SETHORIZONTALEXTENT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_LB_SETHORIZONTALEXTENT 404L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SM_CXVSCROLL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SM_CXVSCROLL 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SM_CYVSCROLL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SM_CYVSCROLL 20L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SM_CYHSCROLL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SM_CYHSCROLL 3L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_SYNC
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_SYNC 0L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_ASYNC
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_ASYNC 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_NODEFAULT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_NODEFAULT 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_LOOP
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_LOOP 8L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_PURGE
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_PURGE 64L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_FILENAME
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_SND_FILENAME 131072L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_ARCHIVE
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_ARCHIVE 32L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_DIRECTORY
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_DIRECTORY 16L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_HIDDEN
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_HIDDEN 2L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_NORMAL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_NORMAL 128L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_READONLY
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_READONLY 1L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_SYSTEM
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_FILE_ATTRIBUTE_SYSTEM 4L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_VK_SHIFT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_VK_SHIFT 16L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_VK_CTRL
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_VK_CTRL 17L
#undef net_sf_eclipsensis_util_winapi_x64_WinAPI64_VK_ALT
#define net_sf_eclipsensis_util_winapi_x64_WinAPI64_VK_ALT 18L
/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    SetWindowLong
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_SetWindowLong
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    GetWindowLong
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_GetWindowLong
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    SetWindowLongPtr
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_SetWindowLongPtr
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    GetWindowLongPtr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_GetWindowLongPtr
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    SetLayeredWindowAttributes
 * Signature: (JIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_SetLayeredWindowAttributes
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    GetDesktopWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_GetDesktopWindow
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    HtmlHelp
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_HtmlHelp
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    SendMessage
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_SendMessage
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    CallWindowProc
 * Signature: (JJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_CallWindowProc
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    DrawWidgetThemeBackGround
 * Signature: (JJLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_DrawWidgetThemeBackGround
  (JNIEnv *, jobject, jlong, jlong, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    DrawWidgetThemeBorder
 * Signature: (JJLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_DrawWidgetThemeBorder
  (JNIEnv *, jobject, jlong, jlong, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    PlaySound
 * Signature: (Ljava/lang/String;JI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_PlaySound
  (JNIEnv *, jobject, jstring, jlong, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegQueryStrValue
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegQueryStrValue
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegGetSubKeys
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegGetSubKeys
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegKeyExists
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegKeyExists
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegOpenKeyEx
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegOpenKeyEx
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegCloseKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegCloseKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegQueryInfoKey
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegQueryInfoKey
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegEnumKeyEx
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegEnumKeyEx
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    GetRegValuesCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_GetRegValuesCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x64_WinAPI64
 * Method:    RegEnumValue
 * Signature: (JILnet/sf/eclipsensis/util/RegistryValue;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x64_WinAPI64_RegEnumValue
  (JNIEnv *, jobject, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
