/*******************************************************************************
 * Copyright (c) 2004-2010 Sunil Kamath (IcemanK).
 * All rights reserved.
 * This program is made available under the terms of the Common Public License
 * v1.0 which is available at http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     Sunil Kamath (IcemanK) - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_eclipsensis_util_winapi_x86_WinAPI32 */

#ifndef _Included_net_sf_eclipsensis_util_winapi_x86_WinAPI32
#define _Included_net_sf_eclipsensis_util_winapi_x86_WinAPI32
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: INSTANCE */
/* Inaccessible static: ZERO_HANDLE */
/* Inaccessible static: ZERO_LONGPTR */
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_GWL_EXSTYLE
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_GWL_EXSTYLE -20L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_GWL_STYLE
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_GWL_STYLE -16L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_GWL_WNDPROC
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_GWL_WNDPROC -4L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_NCHITTEST
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_NCHITTEST 132L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_SETFOCUS
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_SETFOCUS 7L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_KEYDOWN
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_KEYDOWN 256L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_CHAR
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_CHAR 258L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_SYSCHAR
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_SYSCHAR 262L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_LWA_COLORKEY
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_LWA_COLORKEY 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_LWA_ALPHA
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_LWA_ALPHA 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_EX_LAYERED
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_EX_LAYERED 524288L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_EX_LAYOUTRTL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_EX_LAYOUTRTL 4194304L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_HH_DISPLAY_TOPIC
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_HH_DISPLAY_TOPIC 0L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_HTTRANSPARENT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_HTTRANSPARENT -1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_SZ
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_SZ 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_EXPAND_SZ
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_EXPAND_SZ 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_BINARY
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_BINARY 3L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_DWORD
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_DWORD 4L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_MULTI_SZ
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_REG_MULTI_SZ 7L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_QUERY_VALUE
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_QUERY_VALUE 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_ENUMERATE_SUB_KEYS
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_ENUMERATE_SUB_KEYS 8L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_WOW64_32KEY
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_WOW64_32KEY 512L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_WOW64_64KEY
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_KEY_WOW64_64KEY 256L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_BS_LEFTTEXT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_BS_LEFTTEXT 32L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_CB_SHOWDROPDOWN
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_CB_SHOWDROPDOWN 335L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_CB_GETDROPPEDSTATE
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_CB_GETDROPPEDSTATE 343L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_PRINT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WM_PRINT 791L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_NONCLIENT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_NONCLIENT 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_CLIENT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_CLIENT 4L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_ERASEBKGND
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_ERASEBKGND 8L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_CHILDREN
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_PRF_CHILDREN 16L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_EP_EDITTEXT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_EP_EDITTEXT 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_ETS_NORMAL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_ETS_NORMAL 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_ETS_DISABLED
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_ETS_DISABLED 4L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_ETS_READONLY
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_ETS_READONLY 6L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_LVP_LISTITEM
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_LVP_LISTITEM 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_LIS_NORMAL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_LIS_NORMAL 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_LIS_DISABLED
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_LIS_DISABLED 4L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_BP_RADIOBUTTON
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_BP_RADIOBUTTON 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_UNCHECKEDNORMAL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_UNCHECKEDNORMAL 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_UNCHECKEDHOT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_UNCHECKEDHOT 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_CHECKEDNORMAL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_CHECKEDNORMAL 5L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_CHECKEDHOT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_RBS_CHECKEDHOT 6L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_TVS_HASBUTTONS
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_TVS_HASBUTTONS 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_TVS_HASLINES
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_TVS_HASLINES 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_COLOR_GRAYTEXT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_COLOR_GRAYTEXT 17L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_COLOR_3DHILIGHT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_COLOR_3DHILIGHT 20L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_HSCROLL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_HSCROLL 1048576L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_VSCROLL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_WS_VSCROLL 2097152L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_LB_SETHORIZONTALEXTENT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_LB_SETHORIZONTALEXTENT 404L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SM_CXVSCROLL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SM_CXVSCROLL 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SM_CYVSCROLL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SM_CYVSCROLL 20L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SM_CYHSCROLL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SM_CYHSCROLL 3L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_SYNC
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_SYNC 0L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_ASYNC
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_ASYNC 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_NODEFAULT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_NODEFAULT 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_LOOP
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_LOOP 8L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_PURGE
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_PURGE 64L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_FILENAME
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_SND_FILENAME 131072L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_ARCHIVE
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_ARCHIVE 32L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_DIRECTORY
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_DIRECTORY 16L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_HIDDEN
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_HIDDEN 2L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_NORMAL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_NORMAL 128L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_READONLY
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_READONLY 1L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_SYSTEM
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_FILE_ATTRIBUTE_SYSTEM 4L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_VK_SHIFT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_VK_SHIFT 16L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_VK_CTRL
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_VK_CTRL 17L
#undef net_sf_eclipsensis_util_winapi_x86_WinAPI32_VK_ALT
#define net_sf_eclipsensis_util_winapi_x86_WinAPI32_VK_ALT 18L
/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    SetWindowLong
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_SetWindowLong
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    GetWindowLong
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_GetWindowLong
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    SetWindowLongPtr
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_SetWindowLongPtr
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    GetWindowLongPtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_GetWindowLongPtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    SetLayeredWindowAttributes
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_SetLayeredWindowAttributes
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    GetDesktopWindow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_GetDesktopWindow
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    HtmlHelp
 * Signature: (ILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_HtmlHelp
  (JNIEnv *, jobject, jint, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    SendMessage
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_SendMessage
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    CallWindowProc
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_CallWindowProc
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    DrawWidgetThemeBackGround
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_DrawWidgetThemeBackGround
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    DrawWidgetThemeBorder
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_DrawWidgetThemeBorder
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    PlaySound
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_PlaySound
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegQueryStrValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegQueryStrValue
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegGetSubKeys
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegGetSubKeys
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegKeyExists
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegKeyExists
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegOpenKeyEx
 * Signature: (ILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegOpenKeyEx
  (JNIEnv *, jobject, jint, jstring, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegCloseKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegCloseKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegQueryInfoKey
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegQueryInfoKey
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegEnumKeyEx
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegEnumKeyEx
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    GetRegValuesCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_GetRegValuesCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_eclipsensis_util_winapi_x86_WinAPI32
 * Method:    RegEnumValue
 * Signature: (IILnet/sf/eclipsensis/util/RegistryValue;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_winapi_x86_WinAPI32_RegEnumValue
  (JNIEnv *, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
