/*******************************************************************************
 * Copyright (c) 2004, 2005 Sunil Kamath (IcemanK).
 * All rights reserved.
 * This program is made available under the terms of the Common Public License
 * v1.0 which is available at http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     Sunil Kamath (IcemanK) - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_eclipsensis_util_WinAPI */

#ifndef _Included_net_sf_eclipsensis_util_WinAPI
#define _Included_net_sf_eclipsensis_util_WinAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_eclipsensis_util_WinAPI_GWL_EXSTYLE
#define net_sf_eclipsensis_util_WinAPI_GWL_EXSTYLE -20L
#undef net_sf_eclipsensis_util_WinAPI_LWA_COLORKEY
#define net_sf_eclipsensis_util_WinAPI_LWA_COLORKEY 1L
#undef net_sf_eclipsensis_util_WinAPI_LWA_ALPHA
#define net_sf_eclipsensis_util_WinAPI_LWA_ALPHA 2L
#undef net_sf_eclipsensis_util_WinAPI_WS_EX_LAYERED
#define net_sf_eclipsensis_util_WinAPI_WS_EX_LAYERED 524288L
#undef net_sf_eclipsensis_util_WinAPI_HH_DISPLAY_TOPIC
#define net_sf_eclipsensis_util_WinAPI_HH_DISPLAY_TOPIC 0L
#undef net_sf_eclipsensis_util_WinAPI_HKEY_CLASSES_ROOT
#define net_sf_eclipsensis_util_WinAPI_HKEY_CLASSES_ROOT -2147483648L
#undef net_sf_eclipsensis_util_WinAPI_HKEY_CURRENT_USER
#define net_sf_eclipsensis_util_WinAPI_HKEY_CURRENT_USER -2147483647L
#undef net_sf_eclipsensis_util_WinAPI_HKEY_LOCAL_MACHINE
#define net_sf_eclipsensis_util_WinAPI_HKEY_LOCAL_MACHINE -2147483646L
#undef net_sf_eclipsensis_util_WinAPI_HKEY_USERS
#define net_sf_eclipsensis_util_WinAPI_HKEY_USERS -2147483645L
/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_eclipsensis_util_WinAPI_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    SetWindowLong
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_WinAPI_SetWindowLong
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    GetWindowLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_WinAPI_GetWindowLong
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    SetLayeredWindowAttributes
 * Signature: (JIIIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_eclipsensis_util_WinAPI_SetLayeredWindowAttributes
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    RegQueryStrValue
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_util_WinAPI_RegQueryStrValue
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    GetDesktopWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_WinAPI_GetDesktopWindow
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    HtmlHelp
 * Signature: (JLjava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_eclipsensis_util_WinAPI_HtmlHelp
  (JNIEnv *, jclass, jlong, jstring, jint, jlong);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    GetUserDefaultLangID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_WinAPI_GetUserDefaultLangID
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    ExtractHtmlHelpAndTOC
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_eclipsensis_util_WinAPI_ExtractHtmlHelpAndTOC
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    GetPluginSymbols
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_sf_eclipsensis_util_WinAPI_GetPluginExports
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sf_eclipsensis_util_WinAPI
 * Method:    SendMessage
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_net_sf_eclipsensis_util_WinAPI_SendMessage
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
