#ifndef _Included_MakeNSISRunner
#define _Included_MakeNSISRunner

#ifdef UNICODE

#include "net_sf_eclipsensis_makensis_MakeNSISDelegateU.h"

#define MakeNSISRunner_init Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_init
#define MakeNSISRunner_destroy Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_destroy
#define MakeNSISRunner_reset Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_reset
#define MakeNSISRunner_getErrors Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getErrors
#define MakeNSISRunner_getOutputFileName Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getOutputFileName
#define MakeNSISRunner_getScriptFileName Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getScriptFileName
#define MakeNSISRunner_getWarnings Java_net_sf_eclipsensis_makensis_MakeNSISDelegateU_getWarnings

#else

#include "net_sf_eclipsensis_makensis_MakeNSISDelegate.h"

#define MakeNSISRunner_init Java_net_sf_eclipsensis_makensis_MakeNSISDelegate_init
#define MakeNSISRunner_destroy Java_net_sf_eclipsensis_makensis_MakeNSISDelegate_destroy
#define MakeNSISRunner_reset Java_net_sf_eclipsensis_makensis_MakeNSISDelegate_reset
#define MakeNSISRunner_getErrors JNICALL Java_net_sf_eclipsensis_makensis_MakeNSISDelegate_getErrors
#define MakeNSISRunner_getOutputFileName Java_net_sf_eclipsensis_makensis_MakeNSISDelegate_getOutputFileName
#define MakeNSISRunner_getScriptFileName Java_net_sf_eclipsensis_makensis_MakeNSISDelegate_getScriptFileName
#define MakeNSISRunner_getWarnings Java_net_sf_eclipsensis_makensis_MakeNSISDelegate_getWarnings

#endif
//JNIEXPORT jint JNI_OnLoad(JavaVM *vm, void *reserved);
#endif